Update Dockerfile
Cribbed a bunch from official WordPress image:
https://hub.docker.com/_/wordpress

diff --git a/build/Dockerfile b/build/Dockerfile
--- a/build/Dockerfile
+++ b/build/Dockerfile
@@ -1,31 +1,87 @@
-FROM ubuntu:16.04
+FROM php:7.2-fpm
 
 ENV TERM=xterm-256color
 
-RUN apt-get update && apt-get install -y \
-    git \
-    subversion \
-    wget \
-    libxml2-dev \
-    ssmtp \
-    imagemagick \
+# install the PHP extensions we need (https://make.wordpress.org/hosting/handbook/handbook/server-environment/#php-extensions)
+RUN set -ex; \
+    \
+    savedAptMark="$(apt-mark showmanual)"; \
+    \
+    apt-get update; \
+    apt-get install -y --no-install-recommends \
+    libjpeg-dev \
     libmagickwand-dev \
-    unzip \
-    iproute2 \
-    libicu-dev \
-    && pecl install imagick \
-    && docker-php-ext-enable imagick \
-    && docker-php-ext-install soap intl \
-    && echo "mailhub=mailcatcher:1025\nUseTLS=NO\nFromLineOverride=YES" > /etc/ssmtp/ssmtp.conf \
-    && apt-get remove -y libmagickwand-dev libxml2-dev libicu-dev \
-    && apt-get autoremove -y \
-    && apt-get clean \
-    && mkdir /var/www/.wp-cli \
-    && chown www-data:www-data /var/www/.wp-cli
+    libpng-dev \
+    ; \
+    \
+    docker-php-ext-configure gd --with-png-dir=/usr --with-jpeg-dir=/usr; \
+    docker-php-ext-install \
+    bcmath \
+    exif \
+    gd \
+    mysqli \
+    opcache \
+    zip \
+    ; \
+    pecl install imagick-3.4.4; \
+    docker-php-ext-enable imagick; \
+    \
+    # reset apt-mark's "manual" list so that "purge --auto-remove" will remove all build dependencies
+    apt-mark auto '.*' > /dev/null; \
+    apt-mark manual $savedAptMark; \
+    ldd "$(php -r 'echo ini_get("extension_dir");')"/*.so \
+    | awk '/=>/ { print $3 }' \
+    | sort -u \
+    | xargs -r dpkg-query -S \
+    | cut -d: -f1 \
+    | sort -u \
+    | xargs -rt apt-mark manual; \
+    \
+    apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false; \
+    rm -rf /var/lib/apt/lists/*
 
-WORKDIR /app
+# set recommended PHP.ini settings
+# see https://secure.php.net/manual/en/opcache.installation.php
+RUN { \
+    echo 'opcache.memory_consumption=128'; \
+    echo 'opcache.interned_strings_buffer=8'; \
+    echo 'opcache.max_accelerated_files=4000'; \
+    echo 'opcache.revalidate_freq=2'; \
+    echo 'opcache.fast_shutdown=1'; \
+    echo 'opcache.enable_cli=1'; \
+    } > /usr/local/etc/php/conf.d/opcache-recommended.ini
+# https://codex.wordpress.org/Editing_wp-config.php#Configure_Error_Logging
+RUN { \
+    echo 'error_reporting = 4339'; \
+    echo 'display_errors = Off'; \
+    echo 'display_startup_errors = Off'; \
+    echo 'log_errors = On'; \
+    echo 'error_log = /dev/stderr'; \
+    echo 'log_errors_max_len = 1024'; \
+    echo 'ignore_repeated_errors = On'; \
+    echo 'ignore_repeated_source = Off'; \
+    echo 'html_errors = Off'; \
+    } > /usr/local/etc/php/conf.d/error-logging.ini
 
-EXPOSE 8080
+# RUN apt-get update && apt-get install -y \
+#     git \
+#     subversion \
+#     wget \
+#     libxml2-dev \
+#     ssmtp \
+#     imagemagick \
+#     libmagickwand-dev \
+#     unzip \
+#     iproute2 \
+#     libicu-dev \
+#     && pecl install imagick \
+#     && docker-php-ext-enable imagick \
+#     && docker-php-ext-install soap intl \
+#     && echo "mailhub=mailcatcher:1025\nUseTLS=NO\nFromLineOverride=YES" > /etc/ssmtp/ssmtp.conf \
+#     && apt-get remove -y libmagickwand-dev libxml2-dev libicu-dev \
+#     && apt-get autoremove -y \
+#     && apt-get clean \
+#     && mkdir /var/www/.wp-cli \
+#     && chown www-data:www-data /var/www/.wp-cli
 
-ADD entry.sh /opt/
-RUN chmod 755 /opt/entry.sh
+VOLUME /var/www/html
